# Generated by Django 3.2.11 on 2022-01-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220128_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middlename',
        ),
    ]
